### ISSUE TITLE
How to link google drive

### ISSUE THREAD

**Issue by AgustinOrdonez** [PKD667/google-drive-linux#1]
I am trying to use this but I have issues regarding how to link google account to it. When I mount the drive I get an empty folder (As expected, since I never logged in. How do I link my drive account to it?

**Comment by sskupin** [comment]
I believe there is a bug in the second line of install.sh. It should read
install -D -v opt/google/drive/libfuse.so $DESTDIR/opt/google/drive/libfuse.so
Then everything works as expected.

**Comment by PKD667** [comment]
> I am trying to use this but I have issues regarding how to link google account to it. When I mount the drive I get an empty folder (As expected, since I never logged in. How do I link my drive account to it?

it should open a browser auth window. IDK why it doesnt work.

**Comment by PKD667** [comment]
> I believe there is a bug in the second line of install.sh. It should read install -D -v opt/google/drive/libfuse.so $DESTDIR/opt/google/drive/libfuse.so Then everything works as expected.

Thanks, i fixed it
